#!/usr/bin/env bash
# =============================================================================
# CartSpoon — First-Run Environment Bootstrap
# =============================================================================
# Sets up a complete local development environment from scratch.
# Run once after cloning the repo.
#
# Usage: bash scripts/setup.sh
# =============================================================================

set -euo pipefail

# ── Colors ────────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

step()  { echo -e "\n${BLUE}▶ $1${NC}"; }
ok()    { echo -e "${GREEN}✓ $1${NC}"; }
warn()  { echo -e "${YELLOW}⚠ $1${NC}"; }
error() { echo -e "${RED}✗ $1${NC}"; exit 1; }

# ── Prerequisites Check ───────────────────────────────────────────────────────
step "Checking prerequisites"

command -v node >/dev/null 2>&1 || error "Node.js not found. Install from https://nodejs.org (v20+)"
command -v python3 >/dev/null 2>&1 || error "Python 3 not found. Install from https://python.org"
command -v docker >/dev/null 2>&1 || error "Docker not found. Install Docker Desktop."
command -v npx >/dev/null 2>&1 || error "npx not found. Run: npm install -g npx"

NODE_VERSION=$(node --version | grep -oE '[0-9]+' | head -1)
if [ "$NODE_VERSION" -lt 20 ]; then
  error "Node.js v20+ required. Current: $(node --version)"
fi
ok "Node.js $(node --version)"

PYTHON_VERSION=$(python3 --version | grep -oE '[0-9]+\.[0-9]+' | head -1)
ok "Python $PYTHON_VERSION"

# Check Poetry
if ! command -v poetry >/dev/null 2>&1; then
  warn "Poetry not found. Installing..."
  curl -sSL https://install.python-poetry.org | python3 -
  export PATH="$HOME/.local/bin:$PATH"
  ok "Poetry installed"
else
  ok "Poetry $(poetry --version)"
fi

# Check Docker is running
if ! docker info >/dev/null 2>&1; then
  error "Docker is not running. Please start Docker Desktop."
fi
ok "Docker running"

# ── Install Dependencies ──────────────────────────────────────────────────────
step "Installing Node.js dependencies"
npm install
ok "Node dependencies installed"

step "Installing Python dependencies (scraper)"
cd apps/scraper
poetry install --no-interaction
cd ../..
ok "Python dependencies installed"

# ── Start Local Supabase ──────────────────────────────────────────────────────
step "Starting local Supabase"
cd supabase

if npx supabase status 2>/dev/null | grep -q "API URL"; then
  warn "Supabase already running — skipping start"
else
  npx supabase start
fi

# Extract connection details
SUPABASE_URL=$(npx supabase status 2>/dev/null | grep "API URL" | awk '{print $3}')
SUPABASE_ANON_KEY=$(npx supabase status 2>/dev/null | grep "anon key" | awk '{print $3}')
SUPABASE_SERVICE_KEY=$(npx supabase status 2>/dev/null | grep "service_role key" | awk '{print $3}')
DB_URL=$(npx supabase status 2>/dev/null | grep "DB URL" | awk '{print $3}')

cd ..
ok "Supabase running at $SUPABASE_URL"

# ── Apply Migrations ──────────────────────────────────────────────────────────
step "Applying database migrations"
cd supabase
npx supabase db push
cd ..
ok "Migrations applied"

# ── Create .env.local ─────────────────────────────────────────────────────────
step "Creating environment files"

WEB_ENV="apps/web/.env.local"
SCRAPER_ENV="apps/scraper/.env"

if [ -f "$WEB_ENV" ]; then
  warn "$WEB_ENV already exists — skipping (delete it to regenerate)"
else
  cat > "$WEB_ENV" << EOF
# Auto-generated by scripts/setup.sh — $(date +%Y-%m-%d)
# Fill in the values marked <REQUIRED>

# Supabase — auto-populated from local Supabase
NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL:-http://localhost:54321}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY:-<from: npx supabase status>}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_KEY:-<from: npx supabase status>}

# Anthropic — get from https://console.anthropic.com
ANTHROPIC_API_KEY=<REQUIRED: sk-ant-...>

# Upstash Redis — create free account at https://upstash.com
UPSTASH_REDIS_REST_URL=<REQUIRED>
UPSTASH_REDIS_REST_TOKEN=<REQUIRED>

# Stripe — use TEST keys from https://dashboard.stripe.com/test
STRIPE_SECRET_KEY=<REQUIRED: sk_test_...>
STRIPE_WEBHOOK_SECRET=<from: stripe listen>
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=<REQUIRED: pk_test_...>
STRIPE_PREMIUM_PRICE_ID=<REQUIRED: price_...>

# Resend — create free account at https://resend.com
RESEND_API_KEY=<REQUIRED: re_...>

# PostHog — optional for local dev, create at https://posthog.com
NEXT_PUBLIC_POSTHOG_KEY=
NEXT_PUBLIC_POSTHOG_HOST=https://us.i.posthog.com

# Local dev settings
CRON_SECRET=local-cron-secret-dev
ALERT_WEBHOOK_URL=
ADMIN_ALLOWED_IPS=127.0.0.1
EOF
  ok "Created $WEB_ENV (fill in <REQUIRED> values)"
fi

if [ -f "$SCRAPER_ENV" ]; then
  warn "$SCRAPER_ENV already exists — skipping"
else
  cat > "$SCRAPER_ENV" << EOF
# Auto-generated by scripts/setup.sh — $(date +%Y-%m-%d)
DATABASE_URL=${DB_URL:-postgresql://postgres:postgres@localhost:54322/postgres}
SCRAPER_SECRET=local-dev-secret
ALERT_WEBHOOK_URL=
SPOONACULAR_API_KEY=<optional: for recipe import>
EOF
  ok "Created $SCRAPER_ENV"
fi

# ── Verify Setup ──────────────────────────────────────────────────────────────
step "Verifying setup"

# TypeScript check
cd apps/web
if npx tsc --noEmit 2>/dev/null; then
  ok "TypeScript check passed"
else
  warn "TypeScript errors — likely missing env vars (normal at this stage)"
fi
cd ../..

# Python tests
cd apps/scraper
if poetry run pytest --tb=short -q 2>/dev/null; then
  ok "Python tests passed"
else
  warn "Some Python tests failed — check output above"
fi
cd ../..

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  CartSpoon setup complete!${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════${NC}"
echo ""
echo "Next steps:"
echo ""
echo "1. Fill in <REQUIRED> values in apps/web/.env.local"
echo "   Minimum needed to run: ANTHROPIC_API_KEY, UPSTASH_*, STRIPE_*"
echo ""
echo "2. Seed recipes (required for meal plan generation):"
echo "   cd apps/scraper && poetry run python -m src.recipe_importer"
echo ""
echo "3. Start the web app:"
echo "   npm run dev"
echo "   Open: http://localhost:3000"
echo ""
echo "4. (Optional) Start scraper service:"
echo "   cd apps/scraper && poetry run python -m src.server"
echo ""
echo "5. View local emails (magic links):"
echo "   http://localhost:54324"
echo ""
echo "6. View Supabase Studio:"
echo "   http://localhost:54323"
echo ""
echo -e "${YELLOW}See docs/ONBOARDING.md for full setup guide.${NC}"
